#!/usr/bin/env bash
# =============================================================================
# HoloQPI - clean the server working copy. The Linux twin of cleanup.cmd.
#
#     bash cleanup.sh              do it
#     bash cleanup.sh --dry-run    print the plan and the bytes, change nothing
#
# It removes the final-epoch checkpoints too (runs/*/last_model.pt, ~2 GB).
# Only best_model.pt is ever read -- evaluation, export, the benchmark and the
# figures all load it. Pass --keep-last to leave them.
#
# Run it from the project root.
#
# WHAT IS REMOVED, AND WHY IT IS NOT JUST CLUTTER
#
# Two categories are actively dangerous to keep, which is the reason this
# exists rather than a one-line rm:
#
#   figures/fig01..09, fig11..15  are plots of the 2026-09-09 QUICK smoke run
#       -- 2 epochs on 192 px crops. They are indistinguishable from results
#       at a glance and they are not results.
#
#   runs/*_modality_comparison.*  are exactly the files make_figures.py looks
#       for when building figures 5, 7, 13 and 14. While they exist, a figure
#       run will draw smoke-test numbers into a paper figure without warning.
#
# Nothing from the 2026-09-14/15 study is removed: every v2 checkpoint, every
# metrics_test.json, runs/RESULTS.md, the current figures and the current logs
# are kept, apart from the final-epoch checkpoints described above.
# =============================================================================

set -u
cd "$(dirname "$0")" || exit 1

APPLY=1
PRUNE_LAST=1
for arg in "$@"; do
  case "${arg}" in
    --dry-run) APPLY="" ;;
    --keep-last) PRUNE_LAST="" ;;
    --apply) APPLY=1 ;;
    *) echo "usage: bash cleanup.sh [--dry-run] [--keep-last]"; exit 2 ;;
  esac
done

if [ ! -f main.py ] || [ ! -f run_v2.sh ]; then
  echo "  Run this from the project root (main.py and run_v2.sh must be here)."
  exit 1
fi

TOTAL=0
PLAN=()

# Queue one path for removal. Records its size so the plan can be totalled.
drop() {
  local path="$1" why="$2" bytes
  [ -e "${path}" ] || return 0
  bytes="$(du -sb "${path}" 2>/dev/null | cut -f1)"
  bytes="${bytes:-0}"
  TOTAL=$((TOTAL + bytes))
  PLAN+=("${bytes}|${path}|${why}")
}

# --- transfer archives -------------------------------------------------------
for f in docs.zip holoqpi_membrane_weights_*.zip holoqpi_v2_changes_*.zip \
         holoqpi_v2_pipeline_*.zip holoqpi_v2_server.tar.gz; do
  drop "${f}" "archive used only to move code between machines"
done

# --- superseded drivers ------------------------------------------------------
# run_all.sh re-evaluated "all four experiments"; run_study.sh was the v1
# five-stage study. Neither knows about the thirteen-arm design. run_v2.sh and
# study.sh replace them.
drop run_all.sh "v1 driver, superseded by run_v2.sh"
drop run_study.sh "v1 driver, superseded by run_v2.sh"
drop .study_driver.sh "runtime copy study.sh makes of itself"

# --- narration from runs that were aborted or superseded ---------------------
for f in full.out pretrain.out reeval.out study.out; do
  drop "${f}" "narration from a superseded run"
done

# --- a script that would now do damage ---------------------------------------
# cleanup_legacy.py removed the paper-1 RBC framework, a job finished weeks
# ago. Its LEGACY_DIRECTORIES list still contains "weights", so running it
# today would delete the ImageNet checkpoint that model.pretrained_dir points
# at, and every arm would then train from scratch while the config still said
# pretrained_encoder: true.
drop scripts/cleanup_legacy.py "would delete weights/ if anyone ran it"

# --- byte-code caches --------------------------------------------------------
while IFS= read -r d; do
  drop "${d}" "python byte-code cache"
done < <(find . -type d -name __pycache__ -not -path "./data/*" 2>/dev/null)

# --- smoke-test figures ------------------------------------------------------
# 1,2,3,4,6,8,9,12,15 are regenerated by the fixed stage 9. The rest are out of
# scope for this study: 5 and 13 need a Gabor arm (deferred to study 2), 7 is
# superseded by figure 19, 11 needs the condition classifier that every v2 arm
# switches off.
for n in 01_qualitative_panel 02_bland_altman 03_error_decomposition \
         04_detection_gap 05_modality_comparison 06_loss_composition \
         07_ablation_deltas 08_efficiency_tradeoff 09_phase_error_structure \
         11_confusion_matrices 12_convergence 13_forward_model_consistency \
         14_learned_vs_classical 15_recall_by_cell_size; do
  drop "figures/fig${n}.png" "plot of the 2026-09-09 smoke run"
  drop "figures/fig${n}.pdf" "plot of the 2026-09-09 smoke run"
done

# --- v1 run directories ------------------------------------------------------
# Every metrics file in these came from a QUICK run: phase_ssim negative,
# seg_dice identical to sixteen digits across four different conditions,
# detection_f1 = nan.
for prefix in base classification_only conventional fixed_threshold \
              no_measurement no_physics physics_coupling_only; do
  for d in runs/"${prefix}"_*; do
    [ -d "${d}" ] && drop "${d}" "v1 smoke-test run directory"
  done
done
drop runs/null_probe "v1 diagnostic run directory"

for f in runs/*_modality_comparison.csv runs/*_modality_comparison.json; do
  drop "${f}" "SMOKE-TEST NUMBERS a figure run would pick up"
done
for f in runs/base_hardware_benchmark_cuda.csv runs/base_hardware_benchmark_cuda.json \
         runs/seed_aggregate.csv runs/seed_aggregate.json \
         runs/label_audit_redundancy.json runs/mass_uncertainty.json; do
  drop "${f}" "superseded by this study's own output"
done

# --- old logs ----------------------------------------------------------------
for f in logs/*.tar.gz; do
  drop "${f}" "tarball of logs that are kept as directories"
done
for d in logs/20260903_034814 logs/20260903_052408 logs/study_2026090*; do
  [ -e "${d}" ] && drop "${d}" "v1 study log"
done
# The v2 attempts before the real run began at 20:56 on 2026-09-14. KEPT:
# v2_20260914_205603, v2_20260914_222427, v2_20260915_055247 and the four
# stage logs from 07:03 onwards -- that is the study.
for d in logs/v2_20260914_1530* logs/v2_20260914_161854 logs/v2_20260914_163720 \
         logs/v2_20260914_164403 logs/v2_20260914_170107 logs/v2_20260914_173553; do
  [ -e "${d}" ] && drop "${d}" "interrupted or superseded v2 attempt"
done

# --- pre-v2 archive ----------------------------------------------------------
# Copies of the smoke-test runs/ and figures/ removed above. Keeping them keeps
# the hazard.
for d in archive/*; do
  [ -e "${d}" ] && drop "${d}" "snapshot of the smoke-test runs/ and figures/"
done

# --- the final-epoch checkpoints (skip with --keep-last) ---------------------
# Only best_model.pt is ever read -- evaluation, export, the benchmark and the
# figures all load it. last_model.pt is kept by training.save_last and is
# useful only to RESUME a stopped arm.
if [ -n "${PRUNE_LAST}" ]; then
  for f in runs/*/last_model.pt; do
    drop "${f}" "final-epoch checkpoint, nothing reads it"
  done
fi

# --- report ------------------------------------------------------------------
printf '\n  HoloQPI cleanup -- %s\n\n' "$(pwd)"
if [ "${#PLAN[@]}" -eq 0 ]; then
  echo "  Nothing to remove; this copy is already clean."
  exit 0
fi

printf '  %10s  %s\n' "SIZE" "PATH"
printf '  %10s  %s\n' "----" "----"
for entry in "${PLAN[@]}"; do
  bytes="${entry%%|*}"; rest="${entry#*|}"
  path="${rest%%|*}"; why="${rest#*|}"
  printf '  %10s  %-52s %s\n' \
    "$(numfmt --to=iec --suffix=B "${bytes}" 2>/dev/null || echo "${bytes}")" \
    "${path}" "${why}"
done
printf '\n  %d item(s), %s\n\n' "${#PLAN[@]}" \
  "$(numfmt --to=iec --suffix=B "${TOTAL}" 2>/dev/null || echo "${TOTAL} bytes")"

if [ -z "${APPLY}" ]; then
  echo "  Dry run. Nothing was removed. Run it without --dry-run to do it."
  echo ""
  exit 0
fi

# Gather every document under docs/.
mkdir -p docs
if [ -d QPI_Extended_Lit ]; then
  mkdir -p docs/literature
  mv -f QPI_Extended_Lit/* docs/literature/ 2>/dev/null
  rmdir QPI_Extended_Lit 2>/dev/null
fi

# Keep this study's narration beside this study's logs.
mkdir -p logs/study
for f in p_main.out p_rest.out p_seeds.out p_rest_eval.out p_finish.out; do
  [ -f "${f}" ] && mv -f "${f}" logs/study/
done

for entry in "${PLAN[@]}"; do
  rest="${entry#*|}"; path="${rest%%|*}"
  rm -rf -- "${path}"
done
rmdir archive 2>/dev/null

# Empty Gabor stubs the export step leaves behind. Plain rmdir, so a Gabor arm
# that ever does get trained is not removed.
for d in runs/v2_*_gabor; do rmdir "${d}" 2>/dev/null; done

printf '  Removed %s.\n\n' \
  "$(numfmt --to=iec --suffix=B "${TOTAL}" 2>/dev/null || echo "${TOTAL} bytes")"
echo "  Project root now holds:"
ls -1 | sed 's/^/    /'
echo ""
